{
 "title": "app logs",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "All logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{compose_service=\"nginx\"} |= `` | pattern `<remote_addr> - - <time_local> \"<method> <endpoint> <_>\" <status> <bites> <_>  \"<agent>\" <_>`"
    }
   ]
  },
  {
   "title": "status",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(status) (rate({compose_service=\"nginx\"} |= `` | pattern `<remote_addr> - - <time_local> \"<method> <endpoint> <_>\" <status> <bites> <_>  \"<agent>\" <_>` [$__interval]))"
    }
   ]
  },
  {
   "title": "methods",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(endpoint) (rate({compose_service=\"nginx\"} |= `` | pattern `<remote_addr> - - <time_local> \"<method> <endpoint> <_>\" <status> <bites> <_>  \"<agent>\" <_>` [$__interval]))"
    }
   ]
  },
  {
   "title": "methods",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(method) (rate({compose_service=\"nginx\"} |= `` | pattern `<remote_addr> - - <time_local> \"<method> <endpoint> <_>\" <status> <bites> <_>  \"<agent>\" <_>` [$__interval]))"
    }
   ]
  }
 ]
}