{
 "title": "FastApi",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "All logs nginx",
   "type": "logs",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{compose_service=\"nginx\"} |= ``"
    }
   ]
  },
  {
   "title": "500",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate({compose_service=\"app\"} |= `500 Internal Server Error` [$__interval]))"
    }
   ]
  },
  {
   "title": "Edpoints",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 4, "y": 7 },
   "targets": [
    {
     "expr": "count(http_request_duration_seconds_bucket{handler=\"/api/login\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(http_request_duration_seconds_bucket{handler=\"/api/tweets\"})"
    },
    {
     "expr": "count(http_request_duration_seconds_bucket{handler=\"/api/tweets/{idx}\"})"
    },
    {
     "expr": "count(http_request_duration_seconds_bucket{handler=\"/api/users/me\"})"
    },
    {
     "expr": "count(http_request_duration_seconds_bucket{handler=\"/api/medias\"})"
    },
    {
     "expr": "count(http_request_duration_seconds_bucket{handler=\"/api/users/{idx}\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "200 OK",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate({compose_service=\"app\"} != `/metrics` [$__interval]))"
    }
   ]
  },
  {
   "title": "404",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate({compose_service=\"app\"} |= `404` [$__interval]))"
    }
   ]
  },
  {
   "title": "All logs app",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "{compose_service=\"app\"} != `/metrics`"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } }
 ]
}