{
 "title": "nginx_promtail",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "filter" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "methods",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(method) (count_over_time({container_name=\"nginx\"} |= `$filter` | json | method =~ `.+` [$__range]))"
    }
   ]
  },
  {
   "title": "status",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(status) (count_over_time({container_name=\"nginx\"} |= `$filter` | status =~ `.+` [$__range]))"
    }
   ]
  },
  {
   "title": "requests",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10, sum by(request) (count_over_time({container_name=\"nginx\"} |= `$filter` | request =~ `.+` [$__range])))"
    }
   ]
  },
  {
   "title": "method-status",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(method, status, request) (count_over_time({container_name=\"nginx\"} |= `$filter` | json | status =~ `.+` [$__range]))"
    }
   ]
  },
  {
   "title": "user agents",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(http_user_agent) (count_over_time({container_name=\"nginx\"} |= `$filter` | json | http_user_agent =~ `.+` [$__range]))"
    }
   ]
  },
  {
   "title": "All logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "{container_name=\"nginx\"} |= ``"
    }
   ]
  }
 ]
}